package com.gfd.dailytrainfacts

object TrainFactsProvider {
    private val facts = listOf(
        "The first steam locomotive was built by Richard Trevithick in 1804.",
        "The fastest train in the world is the Shanghai Maglev, reaching 267 mph.",
        "The Trans-Siberian Railway is the longest railway line in the world.",
        "The first underground railway was the Metropolitan Railway in London, opened in 1863.",
        "Japan's Shinkansen, or 'bullet train', began operation in 1964.",
        "The world's first scheduled passenger steam train service started in 1830.",
        "Standard gauge for most railways is 4 feet 8.5 inches.",
        "The world's highest railway station is Tanggula Railway Station in Tibet.",
        "The Channel Tunnel is the longest undersea tunnel in the world.",
        "The Hogwarts Express in the Harry Potter films is a GWR 4900 Class locomotive.",
        "The first American-built steam locomotive was the Tom Thumb.",
        "Railways were used in mines as early as the 1550s.",
        "The Mallard holds the world speed record for steam locomotives at 126 mph.",
        "The Orient Express originally ran from Paris to Istanbul.",
        "The Big Boy is the largest steam locomotive ever built.",
        "A 'locomotive' is the engine that pulls the train cars.",
        "The world's oldest continuously operating railway is the Middleton Railway in Leeds.",
        "The word 'train' comes from the Old French 'trahiner', meaning to draw or pull.",
        "India's railway network is one of the largest in the world, employing over 1.3 million people.",
        "The first railway bridge was built by George Stephenson.",
        "The 'Golden Spike' joined the First Transcontinental Railroad in the US in 1869.",
        "Electric trains were first introduced in the late 19th century.",
        "The Darjeeling Himalayan Railway is a UNESCO World Heritage site.",
        "The first automated driverless train started operating in 1961.",
        "The Eurostar connects London with Paris and Brussels.",
        "The world's busiest railway station is Shinjuku Station in Tokyo.",
        "Maglev trains use magnets to float above the tracks, reducing friction.",
        "The first diesel-electric locomotive was built in 1914.",
        "The Flying Scotsman was the first steam locomotive to officially reach 100 mph.",
        "The TGV is France's high-speed rail service.",
        "Rail transport is one of the most energy-efficient ways to move goods and people.",
        "The first railroad in the US was the Baltimore and Ohio Railroad.",
        "The 'Rocket' was an early steam locomotive built by Robert Stephenson.",
        "The Australian Trans-Australian Railway has the world's longest straight stretch of track.",
        "The Grand Central Terminal in New York has 44 platforms.",
        "The first dining car was introduced by the Pullman Palace Car Company.",
        "The 'Iron Horse' was a common nickname for early steam locomotives.",
        "The world's first rack railway was the Mount Washington Cog Railway.",
        "The first electric tramway opened in Berlin in 1881.",
        "The 'General' was a famous steam locomotive involved in the Great Locomotive Chase.",
        "The Glacier Express in Switzerland is known as the 'slowest express train'.",
        "The first railway post office ran in the UK in 1838.",
        "The Ghan is a famous passenger train that crosses Australia from north to south.",
        "The first sleeping car was designed by George Pullman.",
        "The world's shortest railway is the Angels Flight in Los Angeles.",
        "The 'Jupiter' was one of the locomotives at the Golden Spike ceremony.",
        "The first railway tunnel was the Terre-Noire Tunnel in France.",
        "The 'Evening Star' was the last steam locomotive built for British Railways.",
        "The first high-speed rail line was the Tokaido Shinkansen in Japan.",
        "The 'Puffing Billy' is the world's oldest surviving steam locomotive.",
        "The first railway signal was a simple board or flag.",
        "The 'Blue Train' is a luxury train service in South Africa.",
        "The first steam-powered passenger railway in the US was the South Carolina Canal and Railroad Company.",
        "The 'Santa Fe' was a famous American railroad company.",
        "The first railway in Africa was built in Egypt in 1854.",
        "The 'Indian Pacific' crosses Australia from Sydney to Perth.",
        "The first railway in South America was built in British Guiana in 1848.",
        "The 'Rocky Mountaineer' is a luxury train service in Canada.",
        "The first railway in Asia was built in India in 1853.",
        "The 'Rovos Rail' is another luxury train service in South Africa.",
        "The first railway in China was the Woosung Railway, built in 1876.",
        "The 'Bernina Express' crosses the Alps between Switzerland and Italy.",
        "The first railway in Japan was the Tokyo-Yokohama line, opened in 1872.",
        "The 'California Zephyr' is a famous Amtrak route in the US.",
        "The first railway in Russia was the Tsarskoye Selo Railway, opened in 1837.",
        "The 'Venice Simplon-Orient-Express' is a modern luxury version of the original.",
        "The first railway in Canada was the Champlain and St. Lawrence Railroad.",
        "The 'Texas Eagle' is another famous Amtrak route.",
        "The first railway in Mexico was the Mexican Railway, opened in 1873.",
        "The 'Coastal Starlight' runs along the West Coast of the US.",
        "The first railway in Brazil was the Mauá Railroad, opened in 1854.",
        "The 'Empire Builder' runs between Chicago and the Pacific Northwest.",
        "The first railway in Argentina was the Buenos Aires Western Railway, opened in 1857.",
        "The 'Sunset Limited' is the oldest continuously operating named train in the US.",
        "The first railway in Chile was the Copiapó-Caldera line, opened in 1851.",
        "The 'Acela' is Amtrak's high-speed service on the Northeast Corridor.",
        "The first railway in Peru was the Lima-Callao line, opened in 1851.",
        "The 'Heartland Flyer' runs between Oklahoma City and Fort Worth.",
        "The first railway in Cuba was the Havana-Bejucal line, opened in 1837.",
        "The 'Silver Meteor' runs between New York City and Miami.",
        "The first railway in Australia was the Melbourne and Hobson's Bay Railway, opened in 1854.",
        "The 'Palmetto' runs between New York City and Savannah.",
        "The first railway in New Zealand was the Ferrymead Railway, opened in 1863.",
        "The 'Crescent' runs between New York City and New Orleans.",
        "The first railway in Indonesia was the Semarang-Tanggung line, opened in 1867.",
        "The 'Cardinal' runs between New York City and Chicago via Cincinnati.",
        "The first railway in Thailand was the Bangkok-Ayutthaya line, opened in 1896.",
        "The 'Capitol Limited' runs between Washington, D.C. and Chicago.",
        "The first railway in Vietnam was the Saigon-Cholon line, opened in 1881.",
        "The 'Auto Train' carries passengers and their automobiles between Virginia and Florida.",
        "The first railway in Malaysia was the Taiping-Port Weld line, opened in 1885.",
        "The 'Northeast Regional' is a busy Amtrak service in the Northeast US.",
        "The first railway in the Philippines was the Manila-Dagupan line, opened in 1892.",
        "The 'Keystone Service' runs between New York City and Harrisburg.",
        "The first railway in Turkey was the Izmir-Aydin line, opened in 1866.",
        "The 'Downeaster' runs between Boston and Brunswick, Maine.",
        "The first railway in Iran was the Tehran-Ray line, opened in 1888.",
        "The 'Vermonter' runs between Washington, D.C. and St. Albans, Vermont.",
        "The first railway in Iraq was the Baghdad-Samarra line, opened in 1914.",
        "The 'Pacific Surfliner' runs along the Southern California coast.",
        "The first railway in Pakistan was the Karachi-Kotri line, opened in 1861.",
        "The 'San Joaquins' runs through California's Central Valley.",
        "The first railway in Sri Lanka was the Colombo-Ambepussa line, opened in 1864.",
        "The 'Hiawatha' runs between Chicago and Milwaukee.",
        "The first railway in Myanmar was the Yangon-Pyay line, opened in 1877.",
        "The 'Wolverine' runs between Chicago and Pontiac, Michigan.",
        "The first railway in Bangladesh was the Darshana-Jagati line, opened in 1862.",
        "The 'Blue Water' runs between Chicago and Port Huron, Michigan.",
        "The first railway in South Korea was the Gyeongin Line, opened in 1899.",
        "The 'Pere Marquette' runs between Chicago and Grand Rapids, Michigan.",
        "The first railway in North Korea was the Gyeongui Line, opened in 1906.",
        "The 'Illinois Service' includes several routes within Illinois.",
        "The first railway in Taiwan was the Keelung-Taipei line, opened in 1891.",
        "The 'Lincoln Service' runs between Chicago and St. Louis.",
        "The first railway in Israel was the Jaffa-Jerusalem line, opened in 1892.",
        "The 'Missouri River Runner' runs between St. Louis and Kansas City.",
        "The first railway in Saudi Arabia was the Dammam-Riyadh line, opened in 1951.",
        "The 'Winter Park Express' is a seasonal ski train in Colorado.",
        "The first railway in Jordan was the Hejaz Railway, opened in 1908.",
        "The 'Ethan Allen Express' runs between New York City and Burlington, Vermont.",
        "The first railway in Lebanon was the Beirut-Damascus line, opened in 1895.",
        "The 'Adirondack' runs between New York City and Montreal.",
        "The first railway in Syria was the Damascus-Mzerib line, opened in 1894.",
        "The 'Maple Leaf' runs between New York City and Toronto.",
        "The first railway in Greece was the Athens-Piraeus line, opened in 1869.",
        "The 'Carolinian' runs between New York City and Charlotte.",
        "The first railway in Bulgaria was the Ruse-Varna line, opened in 1866.",
        "The 'Piedmont' runs between Raleigh and Charlotte.",
        "The first railway in Romania was the Bucharest-Giurgiu line, opened in 1869.",
        "The 'Cascades' runs between Eugene, Oregon and Vancouver, B.C.",
        "The first railway in Serbia was the Belgrade-Nis line, opened in 1884.",
        "The 'Frontrunner' is a commuter rail service in Utah.",
        "The first railway in Croatia was the Kotoriba-Cakovec line, opened in 1860.",
        "The 'Sounder' is a commuter rail service in Washington state.",
        "The first railway in Slovenia was the Sentilj-Celje line, opened in 1846.",
        "The 'Caltrain' is a commuter rail service in the San Francisco Bay Area.",
        "The first railway in Hungary was the Pest-Vac line, opened in 1846.",
        "The 'Metrolink' is a commuter rail service in Southern California.",
        "The first railway in Slovakia was the Bratislava-Trnava line, opened in 1840.",
        "The 'ACE' (Altamont Corridor Express) runs in Northern California.",
        "The first railway in the Czech Republic was the Ceske Budejovice-Linz horse-drawn line.",
        "The 'Coaster' is a commuter rail service in San Diego County.",
        "The first railway in Poland was the Upper Silesian Railway, opened in 1842.",
        "The 'SunRail' is a commuter rail service in Central Florida.",
        "The first railway in Finland was the Helsinki-Hameenlinna line, opened in 1862.",
        "The 'Tri-Rail' is a commuter rail service in South Florida.",
        "The first railway in Norway was the Hoved Line, opened in 1854.",
        "The 'Music City Star' is a commuter rail service in Nashville.",
        "The first railway in Sweden was the Frykstad Railway, opened in 1849.",
        "The 'Northstar' is a commuter rail service in Minneapolis.",
        "The first railway in Denmark was the Copenhagen-Roskilde line, opened in 1847.",
        "The 'Rail Runner' is a commuter rail service in New Mexico.",
        "The first railway in the Netherlands was the Amsterdam-Haarlem line, opened in 1839.",
        "The 'TRE' (Trinity Railway Express) runs between Dallas and Fort Worth.",
        "The first railway in Belgium was the Brussels-Mechelen line, opened in 1835.",
        "The 'DART' (Dallas Area Rapid Transit) light rail system.",
        "The first railway in Luxembourg was the Bettembourg-Luxembourg line, opened in 1859.",
        "The 'METRO' light rail system in Houston.",
        "The first railway in Switzerland was the Zurich-Baden line, opened in 1847.",
        "The 'MAX' light rail system in Portland, Oregon.",
        "The first railway in Austria was the Floridsdorf-Wagram line, opened in 1837.",
        "The 'Link' light rail system in Seattle.",
        "The first railway in Portugal was the Lisbon-Carregado line, opened in 1856.",
        "The 'VTA' light rail system in San Jose, California.",
        "The first railway in Spain was the Barcelona-Mataró line, opened in 1848.",
        "The 'RTD' light rail system in Denver.",
        "The first railway in Italy was the Naples-Portici line, opened in 1839.",
        "The 'TRAX' light rail system in Salt Lake City.",
        "The first railway in Ireland was the Dublin-Kingstown line, opened in 1834.",
        "The 'Valley Metro' light rail system in Phoenix.",
        "The first railway in Scotland was the Monkland and Kirkintilloch Railway, opened in 1826.",
        "The 'METRO' light rail system in Minneapolis.",
        "The first railway in Wales was the Oystermouth Railway, opened in 1807.",
        "The 'Sprinter' light rail system in San Diego County.",
        "The first railway in England was the Stockton and Darlington Railway, opened in 1825.",
        "The 'Blue Line' light rail system in Charlotte.",
        "The first railway in Germany was the Bavarian Ludwig Railway, opened in 1835.",
        "The 'T' light rail system in Pittsburgh.",
        "The first railway in France was the Saint-Étienne to Andrézieux line, opened in 1827.",
        "The 'Muni Metro' light rail system in San Francisco.",
        "The first railway in the United States was the Granite Railway, opened in 1826.",
        "The 'MBTA' light rail system in Boston.",
        "The first railway in Canada was the Champlain and St. Lawrence Railroad, opened in 1836.",
        "The 'SEPTA' light rail system in Philadelphia.",
        "The first railway in Mexico was the Veracruz-Mexico City line, opened in 1873.",
        "The 'GCTA' light rail system in Jersey City.",
        "The first railway in Brazil was the Estrada de Ferro Mauá, opened in 1854.",
        "The 'NFTA' light rail system in Buffalo.",
        "The first railway in Argentina was the Ferrocarril Oeste de Buenos Aires, opened in 1857.",
        "The 'St. Charles Streetcar' in New Orleans is the oldest continuously operating streetcar line.",
        "The first railway in Australia was the Sydney-Parramatta line, opened in 1855.",
        "The 'TECO Line Streetcar' in Tampa.",
        "The first railway in New Zealand was the Christchurch-Ferrymead line, opened in 1863.",
        "The 'Kenosha Streetcar' in Wisconsin.",
        "The first railway in India was the Mumbai-Thane line, opened in 1853.",
        "The 'El Paso Streetcar' in Texas.",
        "The first railway in China was the Woosung Railway, opened in 1876.",
        "The 'M-Line Trolley' in Dallas.",
        "The first railway in Japan was the Shimbashi-Yokohama line, opened in 1872.",
        "The 'Sun Link' streetcar in Tucson.",
        "The first railway in Russia was the Tsarskoye Selo Railway, opened in 1837.",
        "The 'DC Streetcar' in Washington, D.C.",
        "The first railway in South Africa was the Durban-Point line, opened in 1860.",
        "The 'Cincinnati Bell Connector' streetcar.",
        "The first railway in Egypt was the Alexandria-Kafr el-Zayyat line, opened in 1854.",
        "The 'KC Streetcar' in Kansas City.",
        "The first railway in Morocco was the Tetuan-Rio Martin line, opened in 1859.",
        "The 'Detroit QLine' streetcar.",
        "The first railway in Algeria was the Algiers-Blida line, opened in 1862.",
        "The 'Milwaukee Hop' streetcar.",
        "The first railway in Tunisia was the Tunis-La Goulette line, opened in 1872.",
        "The 'Oklahoma City Streetcar'.",
        "The first railway in Ethiopia was the Djibouti-Addis Ababa line, opened in 1917.",
        "The 'Atlanta Streetcar'.",
        "The first railway in Kenya was the Uganda Railway, opened in 1901.",
        "The 'Charlotte CityLYNX Gold Line'.",
        "The first railway in Nigeria was the Lagos-Ibadan line, opened in 1901.",
        "The 'Portland Streetcar' in Oregon.",
        "The first railway in Ghana was the Sekondi-Tarkwa line, opened in 1901.",
        "The 'Seattle Streetcar'.",
        "The first railway in Sudan was the Wadi Halfa-Sarras line, opened in 1875.",
        "The 'Toronto Streetcar' system is the largest in North America.",
        "The first railway in Zimbabwe was the Vryburg-Bulawayo line, opened in 1897.",
        "The 'Melbourne Tram' system is the largest in the world.",
        "The first railway in Zambia was the Bulawayo-Victoria Falls line, opened in 1904.",
        "The 'Vienna Tram' system is one of the largest in the world.",
        "The first railway in Tanzania was the Tanga-Korogwe line, opened in 1902.",
        "The 'Prague Tram' system is very extensive.",
        "The first railway in Uganda was the Uganda Railway, opened in 1901.",
        "The 'Berlin Tram' system is one of the oldest.",
        "The first railway in Angola was the Luanda Railway, opened in 1888.",
        "The 'Budapest Tram' system is known for its yellow cars.",
        "The first railway in Mozambique was the Beira-Umtali line, opened in 1898.",
        "The 'Warsaw Tram' system has a long history.",
        "The first railway in Namibia was the Swakopmund-Windhoek line, opened in 1902.",
        "The 'Milan Tram' system uses many historic cars.",
        "The first railway in Botswana was the Mafeking-Bulawayo line, opened in 1897.",
        "The 'Lisbon Tram' system is famous for its steep routes.",
        "The first railway in Senegal was the Dakar-Saint Louis line, opened in 1885.",
        "The 'Gothenburg Tram' system is the largest in Scandinavia.",
        "The first railway in Ivory Coast was the Abidjan-Niger Railway, opened in 1905.",
        "The 'Zurich Tram' system is a key part of the city's transport.",
        "The first railway in Cameroon was the Douala-Nkongsamba line, opened in 1911.",
        "The 'Brussels Tram' system is very well integrated.",
        "The first railway in Gabon was the Trans-Gabon Railway, opened in 1978.",
        "The 'Amsterdam Tram' system is iconic.",
        "The first railway in Congo (Kinshasa) was the Matadi-Kinshasa line, opened in 1898.",
        "The 'Antwerp Tram' system has many underground sections.",
        "The first railway in Madagascar was the Tananarive-Tamatave line, opened in 1913.",
        "The 'Oslo Tram' system is called the Oslosprekken.",
        "The first railway in Mauritius was the North line, opened in 1864.",
        "The 'Helsinki Tram' system is very efficient.",
        "The first railway in Reunion was the Saint-Denis to Saint-Pierre line, opened in 1882.",
        "The 'Athens Tram' was rebuilt for the 2004 Olympics.",
        "The first railway in Seychelles was a small industrial line on Silhouette Island.",
        "The 'Istanbul Tram' system includes both modern and nostalgic lines.",
        "The first railway in Cape Verde was a small industrial line on Sal Island.",
        "The 'Alexandria Tram' is one of the oldest in the world.",
        "The first railway in Comoros was a small industrial line on Anjouan Island.",
        "The 'Cairo Tram' system was once very extensive.",
        "The first railway in Mayotte was a small industrial line on Dzaoudzi Island.",
        "The 'Casablanca Tramway' in Morocco.",
        "The first railway in Djibouti was the Djibouti-Addis Ababa line, opened in 1901.",
        "The 'Rabat-Salé Tramway' in Morocco.",
        "The first railway in Eritrea was the Massawa-Asmara line, opened in 1911.",
        "The 'Tunis Tram' system is called the Metro Leger.",
        "The first railway in Ethiopia was the Djibouti-Addis Ababa line, opened in 1917.",
        "The 'Algiers Tramway' in Algeria.",
        "The first railway in Somalia was the Mogadishu-Villabruzzi Railway, opened in 1914.",
        "The 'Oran Tramway' in Algeria.",
        "The first railway in Libya was the Benghazi-Barce line, opened in 1911.",
        "The 'Constantine Tramway' in Algeria.",
        "The first railway in Liberia was the Bomi Hills-Monrovia line, opened in 1951.",
        "The 'Setif Tramway' in Algeria.",
        "The first railway in Sierra Leone was the Freetown-Songo line, opened in 1897.",
        "The 'Sidi Bel Abbes Tramway' in Algeria.",
        "The first railway in Guinea was the Conakry-Kankan line, opened in 1914.",
        "The 'Ouargla Tramway' in Algeria.",
        "The first railway in Togo was the Lome-Aneho line, opened in 1905.",
        "The 'Mostaganem Tramway' in Algeria.",
        "The first railway in Benin was the Cotonou-Ouidah line, opened in 1906.",
        "The 'Luanda Light Rail' is a planned project.",
        "The first railway in Burkina Faso was the Abidjan-Niger Railway, opened in 1933.",
        "The 'Addis Ababa Light Rail' is the first of its kind in sub-Saharan Africa.",
        "The first railway in Mali was the Dakar-Niger Railway, opened in 1904.",
        "The 'Mauritius Metro Express' is a modern light rail system.",
        "The first railway in Niger was the Cotonou-Parakou line, extended to Niamey in 2014.",
        "The 'Gautrain' in South Africa is a high-speed commuter rail.",
        "The first railway in Chad was a small industrial line near Lake Chad.",
        "The 'Lagos Rail Mass Transit' in Nigeria.",
        "The first railway in Central African Republic was a small industrial line.",
        "The 'Abidjan Metro' is an under-construction project.",
        "The first railway in Equatorial Guinea was a small industrial line on Bioko Island.",
        "The 'Dakar Regional Express Train' in Senegal.",
        "The first railway in Sao Tome and Principe was a small industrial line.",
        "The 'Antananarivo-Côte Est' railway in Madagascar.",
        "The first railway in Rwanda was a small industrial line.",
        "The 'Trans-Gabon Railway' is one of the few in Central Africa.",
        "The first railway in Burundi was a small industrial line.",
        "The 'Benguela Railway' connects Angola to the DRC and Zambia.",
        "The first railway in Malawi was the Shire Highlands Railway, opened in 1908.",
        "The 'Tazara Railway' connects Tanzania and Zambia.",
        "The first railway in Swaziland was the Swaziland Railway, opened in 1964.",
        "The 'Blue Train' is famous for its luxury service.",
        "The first railway in Lesotho was the Maseru Branch line, opened in 1905.",
        "The 'Rovos Rail' is often called the 'Pride of Africa'.",
        "The first railway in Gambia was a small industrial line.",
        "The 'Desert Express' is a luxury train in Namibia.",
        "The first railway in Guinea-Bissau was a small industrial line.",
        "The 'Star of the South' is a famous train in Brazil.",
        "The first railway in Cape Verde was a small industrial line.",
        "The 'Tren a las Nubes' in Argentina is one of the highest in the world.",
        "The first railway in Seychelles was a small industrial line.",
        "The 'Old Patagonian Express' is a historic narrow-gauge railway.",
        "The first railway in Saint Helena was the Ladder Hill Railway, opened in 1829.",
        "The 'Belmond Hiram Bingham' runs to Machu Picchu.",
        "The first railway in Falkland Islands was the Camber Railway, opened in 1915.",
        "The 'Vistadome' trains in Peru have panoramic windows.",
        "The first railway in Bermuda was the Bermuda Railway, opened in 1931.",
        "The 'Inca Rail' is another service to Machu Picchu.",
        "The first railway in Bahamas was a small industrial line.",
        "The 'Great Brazil Expressway' is a notable freight route.",
        "The first railway in Jamaica was the Western Jamaica Connecting Railway, opened in 1845.",
        "The 'South Passage' is a famous Australian sailing ship (wait, that's not a train).",
        "The first railway in Barbados was the Barbados Railway, opened in 1881.",
        "The 'Indian Pacific' crosses the Nullarbor Plain.",
        "The first railway in Trinidad and Tobago was the Trinidad Government Railway, opened in 1876.",
        "The 'Ghan' was named after the Afghan cameliers.",
        "The first railway in Puerto Rico was the Ferrocarril de Circunvalación, opened in 1891.",
        "The 'Overland' runs between Melbourne and Adelaide.",
        "The first railway in Haiti was the Port-au-Prince Tramway, opened in 1878.",
        "The 'Spirit of Queensland' uses tilt-train technology.",
        "The first railway in Dominican Republic was the Samaná-Santiago Railway, opened in 1887.",
        "The 'Prospector' runs between Perth and Kalgoorlie.",
        "The first railway in Saint Kitts and Nevis was the Saint Kitts Sugar Factory Railway, opened in 1912.",
        "The 'AvonLink' is a regional service in Western Australia.",
        "The first railway in Antigua and Barbuda was a sugar railway, opened in 1903.",
        "The 'Merseyrail' is a commuter network in Liverpool.",
        "The first railway in Dominica was a forest railway, opened in 1910.",
        "The 'Northern' is a large train operating company in the UK.",
        "The first railway in Saint Lucia was a sugar railway, opened in 1902.",
        "The 'ScotRail' is the national railway of Scotland.",
        "The first railway in Saint Vincent and the Grenadines was a sugar railway.",
        "The 'Transport for Wales' operates most services in Wales.",
        "The first railway in Grenada was a small industrial line.",
        "The 'CrossCountry' runs long-distance services in the UK.",
        "The first railway in Suriname was the Lawa Railway, opened in 1903.",
        "The 'Great Western Railway' is a famous UK rail brand.",
        "The first railway in Guyana was the Demerara-Berbice Railway, opened in 1848.",
        "The 'LNER' operates on the East Coast Main Line.",
        "The first railway in French Guiana was a small industrial line.",
        "The 'Avanti West Coast' operates on the West Coast Main Line.",
        "The first railway in South Georgia and South Sandwich Islands was a whaling railway.",
        "The 'Southeastern' operates services in Kent and East Sussex.",
        "The first railway in British Indian Ocean Territory was a small industrial line.",
        "The 'South Western Railway' operates out of London Waterloo.",
        "The first railway in Christmas Island was a phosphate railway.",
        "The 'Chiltern Railways' operates out of London Marylebone.",
        "The first railway in Nauru was a phosphate railway, opened in 1907.",
        "The 'Greater Anglia' operates services in East Anglia.",
        "The first railway in Fiji was a sugar railway, opened in 1882.",
        "The 'c2c' operates services between London and Shoeburyness.",
        "The first railway in Solomon Islands was a small industrial line.",
        "The 'Thameslink' runs through London from north to south.",
        "The first railway in Vanuatu was a small industrial line.",
        "The 'Southern' operates services in South London and the South Coast.",
        "The first railway in New Caledonia was the Noumea-Paita line, opened in 1901.",
        "The 'Gatwick Express' is a dedicated airport service.",
        "The first railway in Guam was a small military railway.",
        "The 'Heathrow Express' is another dedicated airport service.",
        "The first railway in Northern Mariana Islands was a small industrial line.",
        "The 'Stansted Express' connects London to Stansted Airport.",
        "The first railway in American Samoa was a small military railway.",
        "The 'East Midlands Railway' operates services in the Midlands.",
        "The first railway in Palau was a small industrial line.",
        "The 'West Midlands Railway' operates local services in the West Midlands.",
        "The first railway in Marshall Islands was a small industrial line.",
        "The 'TransPennine Express' connects major cities in the North.",
        "The first railway in Kiribati was a small industrial line.",
        "The 'Grand Central' is an open-access operator in the UK.",
        "The first railway in Tuvalu was a small industrial line.",
        "The 'Hull Trains' is another open-access operator.",
        "The first railway in Micronesia was a small industrial line.",
        "The 'Eurostar' connects the UK to mainland Europe.",
        "The first railway in Tonga was a small industrial line.",
        "The 'Irish Rail' is the national railway of Ireland.",
        "The first railway in Samoa was a small industrial line.",
        "The 'Translink' operates rail services in Northern Ireland.",
        "The first railway in Niue was a small industrial line.",
        "The 'SNCF' is the national railway of France.",
        "The first railway in Cook Islands was a small industrial line.",
        "The 'Deutsche Bahn' is the national railway of Germany.",
        "The first railway in Wallis and Futuna was a small industrial line.",
        "The 'Renfe' is the national railway of Spain.",
        "The first railway in Tokelau was a small industrial line.",
        "The 'Trenitalia' is the national railway of Italy.",
        "The first railway in Pitcairn Islands was a small industrial line.",
        "The 'SBB CFF FFS' is the national railway of Switzerland.",
        "The first railway in Norfolk Island was a small industrial line.",
        "The 'ÖBB' is the national railway of Austria.",
        "The first railway in Easter Island was a small industrial line.",
        "The 'NMBS/SNCB' is the national railway of Belgium.",
        "The first railway in Galapagos Islands was a small industrial line.",
        "The 'NS' is the national railway of the Netherlands.",
        "The 'Big Boy' locomotive 4014 is the only one currently operating."
    )

    fun getFactForDay(dayOfYear: Int): String {
        // Ensure index is within bounds (1-366)
        val index = (dayOfYear - 1) % facts.size
        return facts[index]
    }
}
