package com.gfd.dailytrainfacts

object TrainFactsProvider {
    val facts = listOf(
        "The first steam locomotive was built by Richard Trevithick in 1804.",
        "The fastest operational train in the world is the Shanghai Maglev, reaching 267 mph.",
        "The Trans-Siberian Railway is the longest railway line in the world.",
        "The first underground railway was the Metropolitan Railway in London, opened in 1863.",
        "Japan's Shinkansen, or 'bullet train', began operation in 1964.",
        "The world's first scheduled passenger steam train service started in 1830.",
        "Standard gauge for most railways is 4 feet 8.5 inches.",
        "The world's highest railway station is Tanggula Railway Station in Tibet.",
        "The Channel Tunnel is the longest undersea tunnel in the world.",
        "The Hogwarts Express in the Harry Potter films is a GWR 4900 Class locomotive.",
        "St. Pancras International is home to the longest champagne bar in Europe.",
        "Railways were used in mines as early as the 1550s.",
        "The Orient Express originally ran from Paris to Istanbul.",
        "The Big Boy is the largest steam locomotive ever built.",
        "A 'locomotive' is the engine that pulls the train cars.",
        "The world's oldest continuously operating railway is the Middleton Railway in Leeds.",
        "The word 'train' comes from the Old French 'trahiner', meaning to draw or pull.",
        "India's railway network is one of the largest in the world, employing over 1.3 million people.",
        "The first railway bridge was built by George Stephenson.",
        "The Dawlish sea wall in Devon is one of the most scenic railway lines in England.",
        "Electric trains were first introduced in the late 19th century.",
        "The Darjeeling Himalayan Railway is a UNESCO World Heritage site.",
        "The first automated driverless train started operating in 1961.",
        "The Eurostar connects London with Paris and Brussels.",
        "The world's busiest railway station is Shinjuku Station in Tokyo.",
        "Maglev trains use magnets to float above the tracks, reducing friction.",
        "The first diesel-electric locomotive was built in 1914.",
        "The Flying Scotsman was the first steam locomotive to officially reach 100 mph.",
        "The TGV is France's high-speed rail service.",
        "The Nottingham Express Transit (NET) is called a tram but is technically a light rail system serving Nottingham and Nottinghamshire.",
        "Paddington Station was the London terminus for Brunel's Great Western Railway.",
        "The 'Rocket' was an early steam locomotive built by Robert Stephenson.",
        "The Trans-Australian Railway has the world's longest straight stretch of track.",
        "The Grand Central Terminal in New York has 44 platforms.",
        "The first dining car was introduced by the Pullman Palace Car Company.",
        "The 'Iron Horse' was a common nickname for early steam locomotives.",
        "The world's first rack railway was the Mount Washington Cog Railway.",
        "The first electric tramway opened in Berlin in 1881.",
        "St. Pancras Station's Barlow shed was the largest single-span structure in the world in 1868.",
        "The Glacier Express in Switzerland is known as the 'slowest express train'.",
        "The first railway postal service ran in the UK in 1838.",
        "The Ghan is a famous passenger train that crosses Australia from north to south.",
        "The first sleeping car was designed by George Pullman.",
        "The world's shortest railway is the Angels Flight in Los Angeles.",
        "The South Devon Railway is a heritage railway running between Totnes and Buckfastleigh.",
        "The first railway tunnel was the Terre-Noire Tunnel in France.",
        "The 'Evening Star' was the last steam locomotive built for British Railways.",
        "The first high-speed rail line was the Tokaido Shinkansen in Japan.",
        "The 'Puffing Billy' is the world's oldest surviving steam locomotive.",
        "The first railway signal was a simple board or flag.",
        "The 'Blue Train' is a luxury train service in South Africa.",
        "Nottingham Station was first opened in 1848 by the Midland Railway.",
        "The Great Western Railway was designed by Isambard Kingdom Brunel.",
        "The first railway in Africa was built in Egypt in 1854.",
        "The 'Indian Pacific' crosses Australia from Sydney to Perth.",
        "The 'Cornish Riviera Express' has been running from London to Penzance since 1904.",
        "The 'Rocky Mountaineer' is a luxury train service in Canada.",
        "The first railway in Asia was built in India in 1853.",
        "The 'Rovos Rail' is ar luxury train service in South Africa.",
        "The first railway in China was the Woosung Railway, built in 1876.",
        "The 'Bernina Express' crosses the Alps between Switzerland and Italy.",
        "The first railway in Japan was the Tokyo-Yokohama line, opened in 1872.",
        "The Lynton and Barnstaple Railway in Devon was a famous narrow-gauge line.",
        "The first railway in Russia was the Tsarskoye Selo Railway, opened in 1837.",
        "The 'Venice Simplon-Orient-Express' is a modern luxury version of the original.",
        "The 'Night Riviera' sleeper train runs from London Paddington to Penzance.",
        "The West Highland Line is often voted one of the most beautiful railway journeys.",
        "The Settle-Carlisle line is famous for the iconic Ribblehead Viaduct.",
        "The Great Central Railway is the UK's only double-track heritage main line.",
        "The Forth Bridge in Scotland is a UNESCO World Heritage site.",
        "The Glenfinnan Viaduct is famous for its appearance in the Harry Potter films.",
        "The Jacobite Steam Train runs from Fort William to Mallaig in Scotland.",
        "The first railway in Australia was the Melbourne and Hobson's Bay Railway, opened in 1854.",
        "The Snowdon Mountain Railway is the only rack and pinion railway in the UK.",
        "The first railway in New Zealand was the Ferrymead Railway, opened in 1863.",
        "The Ffestiniog Railway in Wales is the world's oldest narrow-gauge railway.",
        "The 'Caledonian Sleeper' runs from London to various destinations in Scotland.",
        "The Bluebell Railway was the first preserved standard-gauge heritage line in the UK.",
        "The Talyllyn Railway was the first railway in the world to be preserved by volunteers.",
        "The Keighley & Worth Valley Railway was a filming location for 'The Railway Children'.",
        "London Victoria station serves over 70 million passengers a year.",
        "The Severn Valley Railway is one of the most popular heritage lines in the UK.",
        "Waterloo Station has the largest number of platforms in the UK (24).",
        "The Paignton and Dartmouth Steam Railway offers beautiful views of the Devon coast.",
        "The Great Northern Railway once connected Nottingham to London King's Cross.",
        "The British Rail Class 43 (HST) is the fastest diesel train in the world.",
        "The North Yorkshire Moors Railway runs through 24 miles of stunning national park.",
        "The Swanage Railway in Dorset was rebuilt from scratch by volunteers.",
        "The 'Brighton Belle' was the world's first all-electric Pullman train.",
        "The Isle of Wight Steam Railway uses vintage locomotives and carriages.",
        "The 'Golden Arrow' was a luxury boat train that linked London and Paris.",
        "The Romney, Hythe & Dymchurch Railway is a famous 15-inch gauge line.",
        "The 'Master Cutler' is a named express train running between London and Sheffield.",
        "The 'Flying Scotsman' service has run between London and Edinburgh since 1862.",
        "The Ravenglass and Eskdale Railway is one of the oldest and longest narrow-gauge lines.",
        "The first railway in Greece was the Athens-Piraeus line, opened in 1869.",
        "The 'Tees-Thames' express once connected Saltburn to London.",
        "The 'Devonian' express historically ran from Bradford to Paignton.",
        "The 'Robin Hood Line' connects Nottingham to Worksop.",
        "The first railway in Serbia was the Belgrade-Nis line, opened in 1884.",
        "King's Cross Station is famous for its fictional Platform 9¾.",
        "The first railway in Croatia was the Kotoriba-Cakovec line, opened in 1860.",
        "The 'Pines Express' once ran from Manchester to Bournemouth via Bath.",
        "The 'Thames-Clyde Express' linked London St Pancras and Glasgow Central.",
        "The first railway in Hungary was the Pest-Vac line, opened in 1846.",
        "The 'Royal Scot' was a premier express train of the London Midland and Scottish Railway.",
        "The 'Midland Main Line' connects London St Pancras to the East Midlands.",
        "The first railway in the Czech Republic was the Ceske Budejovice-Linz horse-drawn line.",
        "The first railway in Poland was the Upper Silesian Railway, opened in 1842.",
        "The first railway in Finland was the Helsinki-Hameenlinna line, opened in 1862.",
        "The 'West Coast Main Line' connects London Euston to Glasgow Central.",
        "The first railway in Norway was the Hoved Line, opened in 1854.",
        "The first railway in Sweden was the Frykstad Railway, opened in 1849.",
        "The 'Cross Country' network is the most extensive in the UK.",
        "The 'Great Eastern Main Line' connects London Liverpool Street to Norwich.",
        "The first railway in the Netherlands was the Amsterdam-Haarlem line, opened in 1839.",
        "The 'Chiltern Main Line' runs from London Marylebone to Birmingham.",
        "The first railway in Belgium was the Brussels-Mechelen line, opened in 1835.",
        "The 'Docklands Light Railway' (DLR) is an automated system in East London.",
        "The first railway in Switzerland was the Zurich-Baden line, opened in 1847.",
        "The 'Tyne & Wear Metro' serves Newcastle upon Tyne and surrounding areas.",
        "The first railway in Austria was the Floridsdorf-Wagram line, opened in 1837.",
        "The 'Glasgow Subway' is the third oldest underground system in the world.",
        "The first railway in Portugal was the Lisbon-Carregado line, opened in 1856.",
        "The first railway in Spain was the Barcelona-Mataró line, opened in 1848.",
        "The 'West Highland Line' features the spectacular Glenfinnan Viaduct.",
        "The first railway in Italy was the Naples-Portici line, opened in 1839.",
        "The 'Far North Line' is the northernmost railway in the UK.",
        "The first railway in Ireland was the Dublin-Kingstown line, opened in 1834.",
        "The 'Heart of Wales Line' is a scenic rural railway.",
        "The first railway in Scotland was the Monkland and Kirkintilloch Railway, opened in 1826.",
        "The 'Cambrian Line' offers beautiful views of the Welsh coast.",
        "The first railway in Wales was the Oystermouth Railway, opened in 1807.",
        "The 'Hope Valley Line' connects Sheffield and Manchester through the Peak District.",
        "The first railway in England was the Stockton and Darlington Railway, opened in 1825.",
        "The 'Riviera Line' runs along the coast from Exeter to Paignton.",
        "The first railway in Germany was the Bavarian Ludwig Railway, opened in 1835.",
        "The first railway in France was the Saint-Étienne to Andrézieux line, opened in 1827.",
        "The 'Fen Line' connects Cambridge and King's Lynn.",
        "The first railway in the United States was the Granite Railway, opened in 1826.",
        "The 'Poppy Line' is a heritage railway in North Norfolk.",
        "The first railway in Canada was the Champlain and St. Lawrence Railroad, opened in 1836.",
        "The 'Watercress Line' is a heritage railway in Hampshire.",
        "The 'Spa Valley Railway' is a heritage line in Kent.",
        "The first railway in Brazil was the Estrada de Ferro Mauá, opened in 1854.",
        "The 'Epping Ongar Railway' is the longest heritage line in Essex.",
        "The first railway in Argentina was the Ferrocarril Oeste de Buenos Aires, opened in 1857.",
        "The 'St. Charles Streetcar' in New Orleans is the oldest continuously operating streetcar line.",
        "The first railway in Australia was the Sydney-Parramatta line, opened in 1855.",
        "The 'Manx Electric Railway' on the Isle of Man is a historic interurban line.",
        "The first railway in New Zealand was the Christchurch-Ferrymead line, opened in 1863.",
        "The 'Snaefell Mountain Railway' is the only electric mountain railway in the British Isles.",
        "The first railway in India was the Mumbai-Thane line, opened in 1853.",
        "The 'Douglas Bay Horse Tramway' is one of the last remaining of its kind.",
        "The 'Volk's Electric Railway' in Brighton is the oldest electric railway in the world.",
        "The 'Hythe Pier Railway' is the oldest continuously operating pier railway.",
        "The 'Lynton & Lynmouth Cliff Railway' is water-powered.",
        "The first railway in South Africa was the Durban-Point line, opened in 1860.",
        "The 'Babbacombe Cliff Railway' in Devon is a famous funicular.",
        "The 'South Cliff Lift' in Scarborough was the first funicular in the UK.",
        "The 'Bridgnorth Cliff Railway' is one of the oldest inland funiculars.",
        "The 'East Hill Lift' in Hastings is the steepest funicular in the UK.",
        "The 'Leas Lift' in Folkestone is a unique water-balance funicular.",
        "The 'Saltburn Cliff Lift' is one of the oldest water-balanced funiculars in operation.",
        "The 'Southend Pier Railway' is the longest pier railway in the world.",
        "The 'Seaton Tramway' in Devon operates narrow-gauge trams.",
        "The 'Crich Tramway Village' is home to the National Tramway Museum.",
        "The 'Blackpool Tramway' is the only remaining first-generation tramway in the UK.",
        "The 'Edinburgh Trams' returned to the city streets in 2014.",
        "The 'Manchester Metrolink' is the largest light rail system in the UK.",
        "The 'Sheffield Supertram' features a unique design.",
        "The 'Grand Junction Railway' once linked Birmingham to the Liverpool & Manchester Railway.",
        "The 'London and North Western Railway' was once the largest joint-stock company in the world.",
        "The 'Midland Railway' had its headquarters in Derby, near Nottingham.",
        "The 'North Eastern Railway' had the largest collection of steam locomotives in the UK.",
        "The 'Great South & West Railway' was the largest railway in Ireland.",
        "The 'Somerset & Dorset Joint Railway' was famously known as the 'Slow and Dirty'.",
        "The 'Lancashire & Yorkshire Railway' had a very dense network of lines.",
        "The 'London, Brighton and South Coast Railway' was famous for its elegant locomotives.",
        "The 'Great North of Scotland Railway' served the north-east of the country.",
        "The 'Highland Railway' struggled with steep gradients and snowy weather.",
        "The 'Cambrian Railways' served the heart of Wales.",
        "The 'Rhymney Railway' was a key coal-carrying line in South Wales.",
        "The 'Taff Vale Railway' was a major coal-carrying line.",
        "The 'Barry Railway' built its own dock to compete with Cardiff.",
        "The 'Maryport & Carlisle Railway' was a small but profitable line.",
        "The 'North Staffordshire Railway' was known as the 'Knotty'.",
        "The 'Hull & Barnsley Railway' was built to break the monopoly of the NER.",
        "The 'Stratford-upon-Avon & Midland Junction Railway' was formed from several small lines.",
        "The 'Isle of Wight Railway' served the eastern part of the island.",
        "The 'Midland Great Western Railway' was the third largest in Ireland.",
        "The 'Dublin & South Eastern Railway' was known for its scenic coastal line.",
        "The 'Clogher Valley Railway' was a famous Irish narrow-gauge line.",
        "The 'Listowel & Ballybunion Railway' was a unique Lartigue monorail.",
        "The 'Schull & Skibbereen Railway' was a notable Irish narrow-gauge line.",
        "The 'Tralee & Dingle Light Railway' was the westernmost railway in Europe.",
        "The 'County Donegal Railways' had the largest narrow-gauge system in Ireland.",
        "The 'London & Greenwich Railway' was the first to be built on a brick viaduct.",
        "The 'London & Blackwall Railway' originally used cable haulage.",
        "The 'Eastern Counties Railway' was notorious for its poor service.",
        "The 'South Eastern & Chatham Railway' was a working union of two rivals.",
        "The 'Great Central' motto was 'Forward'.",
        "The 'Great Western' motto was 'Domine Dirige Nos'.",
        "The 'Southern' motto was 'Semper Sursum'.",
        "The 'London Midland & Scottish' was formed during the 1923 grouping.",
        "The 'London & North Eastern' was one of the 'Big Four' early British rail companies.",
        "The 'Southern Railway' was the smallest of the Big Four.",
        "The 'Great Western Railway' was the only one to keep its name in 1923.",
        "'British Railways' was formed by nationalisation in 1948.",
        "The 'InterCity 125' was a revolutionary high-speed diesel train.",
        "The 'Advanced Passenger Train' (APT) was a tilt-train that was ahead of its time.",
        "The 'Eurostar' started running through the Channel Tunnel in 1994.",
        "The 'High Speed 1' (HS1) connects London St Pancras to the Channel Tunnel.",
        "The 'Crossrail' project created the Elizabeth Line in London.",
        "The 'Southern' network is the busiest in the UK.",
        "The 'South Western Railway' operates the busiest station in the UK (Waterloo).",
        "The 'Avanti West Coast' service features high-speed tilting trains.",
        "The 'LNER' Azuma trains are some of the fastest in the UK.",
        "The 'Great Western Railway' uses IET trains inspired by Japanese technology.",
        "The 'c2c' service between London and Essex is known for its reliability.",
        "The first railway in South Georgia and South Sandwich Islands was a whaling railway.",
        "The 'Chiltern Railways' is known for its high customer satisfaction.",
        "The first railway in Christmas Island was a phosphate railway.",
        "The 'London Underground' has 11 lines and 272 stations.",
        "The 'Glasgow Subway' is known affectionately as the 'Clockwork Orange'.",
        "The 'Tyne & Wear Metro' uses a unique mix of heavy and light rail technology.",
        "The 'Docklands Light Railway' was originally built using existing railway infrastructure.",
        "The first railroad in the US was the Baltimore and Ohio Railroad.",
        "The 'Humber Bridge' was never designed to carry a railway.",
        "The 'Forth Bridge' is iconic for its cantilever design.",
        "The 'Tay Bridge Disaster' in 1879 led to the design of the current bridge.",
        "The 'Ribblehead Viaduct' is 400 metres long and has 24 arches.",
        "The 'Glenfinnan Viaduct' has 21 arches.",
        "The 'Bennerley Viaduct' near Nottingham is a rare iron structure.",
        "The 'St. Pancras Hotel' is a masterpiece of Gothic Revival architecture.",
        "'Victoria Station' in Nottingham once had a very deep tunnel.",
        "The first American-built steam locomotive was the Tom Thumb.",
        "The 'Old Dalby Test Track' is a key facility for testing new trains in the UK.",
        "The 'Great Western' is often called 'God's Wonderful Railway'.",
        "The 'Dawlish Sea Wall' is one of Brunel's most daring engineering feats.",
        "The 'Midland Main Line' was electrified to Corby in 2021.",
        "The 'Big Boy' locomotive 4014 is the largest operating steam locomotive in the world.",
        "The first railway in South America was built in British Guiana in 1848.",
        "The 'Budapest Tram' system is known for its yellow cars.",
        "The 'Tren a las Nubes' in Argentina is one of the highest railways in the world.",
        "Only one locomotive has flown across the Atlantic Ocean - a test locomotive for Iarnród Éireann was delivered to Dublin from the USA by air.",
        "Brake vans only officially became obsolete in 2021.",
        "The Northern Line of the London Underground is not the tube line that goes furthest north, but is the tube line that goes furthest south.",
        "The Bucharest to Chisinau sleeper, is the last soviet era built train running within Europe. When it gets to the border the have to swap the wheels over due to different track gauges.",
        "Oliver Bulleid's final steam locomotive, CC1, was designed to burn turf.",
        "In the late 19th century, the London and North Western Railway was the largest public company in the world, measured by market value.",
        "The platforms at Long Eaton station are too short to accommodate the Meridian trains used by EMR intercity services.",
        "EMR Meridian unit number 222104 is the only one in its class to have a full purple livery.",
        "The largest station in the UK to close, in terms of platform numbers, was Blackpool Central with 14 platforms.",
        "A large proportion of Transport for Wales Class 150 trains have a piece of black tape in the top right corner of the front windscreen for an unknown reason.",
        "In the village of Brundall in Norfolk, a local railway information sign is located a 15-minute walk from the actual station.",
        "A few original British Rail-era signs survive today, including one at Saltaire, one at London Paddington (Platform 12), and one at Warminster.",
        "The fastest train in the world is Japan’s L0 Series Maglev, which set a new world speed record in 2015, reaching an astonishing 375mph (603 km/h).",
        "The longest direct rail journey in the world is The Trans-Siberian Railway in Russia. It starts in Moscow and takes passengers all the way to Vladivostok. Spanning 5,771 miles (9,290 km) and crossing eight time zones, the journey includes 140 stops and takes a full week if done in one go.",
        "The record for the longest train in the world was broken by the BHP Iron Ore in 2001. The train measured a whopping 4.5 miles long and was made up of 682 wagons.",
        "The record for the longest passenger train in the world goes to Nederlandse Spoorwegen. In 1989, they utilised 60 carriages to create a train 1602 metres long. The train ran from Kijfhoek, a rail yard near Rotterdam, to the city of Eindhoven.",
        "The longest train tunnel in the world is the Gotthard Base Tunnel in Switzerland. It stretches 35.5 miles (57 km) beneath the beautiful Swiss Alps.",
        "George Stephenson built his first steam locomotive in 1814, and it was called 'Blücher'.",
        "The Qinghai-Tibet Railway in China. is the highest railway in the world, reaching 5,072 meters above sea level.",
        "The slowest express service in the world, Switzerland's Glacier Express takes a whooping eight hours to cover a distance of just 181 miles (291km).",
        "The longest journey possible by rail alone is from Porto in Portugal to Singapore. Covering an approximate distance of 10,000 miles (16,000km), the full journey would cost around £5,104 ($7,000) and would take at least 12 days to complete.",
        "Due to complicated legal procedures required to shut a railway line in the UK, it's cheaper to just run a so-called ghost train down the line every now and then. Four current services in the London area run on disused lines that don't stop or take on passengers – Overground to Battersea Park, Overground to Enfield via Stratford, Chiltern to West Ealing and Southeastern to Beckenham.",
        "Totalling 58 letters, the longest station name in the UK is Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch. As it turns out, the name has no historic significance and is a marketing gimmick from the 1880s to attract tourists.",
        "When the railway was first introduced. many people were suspicious of this new form of transport. There were even protests against the running of services on Sunday, the day of rest; by 1889, the Anti-Sunday Travel Union had 8,000 members and nearly 60 branch offices dotted throughout the UK.",
        "The original Eurostar design was heavily determined by the safety regulations in the channel tunnel. This includes the length of the train, which is much longer than usual so that some part of the train is always adjacent to an emergency exit if it has to stop in the tunnel.",
        "The Palmerston North - Gisborne Line in New Zealand crosses the main runway of the Gisborne Airport, with aircraft having right of way over trains.",
        "The Siemens Eurosprinter (ES64 locomotive) is the Fastest Electric Locomotive in Operation, reaching speeds up to 357 Kph in testing.",
        "The football team Manchester United was originally founded as the Newton Heath Lancashire and Yorkshire Railway Football Club, and they wore the railway's livery as their strip",
        "The world record for steam of 126 mph was set on 3rd July 1938 by the LNER A4 no. 4468 'Mallard.' It still stands today.",
        "The platform at Gloucester Station is the longest in the UK. Measuring 1977ft long, it opened in 1977.",
        "The British Royal Train transports the most senior members of the British Royal Family and their staff throughout the country.",
        "The first member of the British royal family to travel by train was the Dowager Queen Adelaide, who took a train from Nottingham to Leeds on 22 July 1840.",
        "Queen Victoria was the first reigning British monarch to travel by train, on 13 June 1842.",
        "Vatican City possesses the shortest national railway system in the world, with just 330m of main line track.",
        "The first Pope to travel by rail was Pope Pius IX, who had his own private train built in 1859.",
        "Pope Gregory XVI (died 1846)was opposed to the building of railways and was reputed to have said 'chemin de fer, chemin d'enfer' ('road of iron, road of hell').",
        "The first modern train ferry was Leviathan, built in 1849 and operated in the Firth of Forth, Scotland.",
        "A train ferry is a ship fitted with railway lines and designed to carry railway vehicles, as well as their cargoes and passengers.",
        "Mankara Airport in East Madagascar is the only remaining airport in the world in which an active railway line crosses the runway.",
        "In North American railway parlance, a level crossing is known as a 'grade crossing'.",
        "The first Season Tickets in the world were issued at Canterbury West Station in 1834 and covered travel between Canterbury and Whitstable for the period between 25th March and 1st November. They cost two guineas.",
        "The area of contact between each wheel and the rail is only about 18mm.",
        "Currently England has over 15 thousand kilometers of working railways, with 14353 used for passenger trains.",
        "The longest stretch of straight railway track is located in Australia and is 478 kilometers long.",
        "70% of all train journeys in England either start or finish in London.",
        "Thomas the Tank Engine first appeared in 1945 and has since become a beloved character around the world.",
        "The final rail connection between Belfast and Dublin was completed in 1852.",
        "While awaiting construction of a new station building, Great Western Railways operated a ticket office out of a hollow oak tree at Moreton on Lugg station.",
        "The record for the fastest built steam locomotive was 9 hours 47 minutes, set by Stratford Works in 1891.",
        "The railway gun 'Schwerer Gustav' was the largest-calibre rifled weapon ever used in combat, and in terms of weight, the heaviest mobile artillery piece ever built, at nearly 1,350 tonnes.",
        "The 'Steam Horse' was an early locomotive built in Derbyshire in 1813 by William Brunton of the Butterley Company. Also known as the Mechanical Traveller, it had a pair of mechanical legs to push it forwards along the rails at about three miles an hour.",
        "Trains shaking as they travel is partly due to a phenomenon called hunting oscillation which causes the wheels to move and can even lead to derailment.",
        "The baked potato was not a particularly common dish in United States cuisine until Northern Pacific introduced the Great Big Baked Potato in their dining cars in 1908.",
        "The budget of the Pennsylvania Railroad was, for a time, greater than the budget of the US Government.",
        "Locomotives used to be crashed head on into one another as a form of entertainment in the US at fairs and events until the mid 1900s.",
        "Australia maintains four different rail gauges in widespread (>1000km) active use.",
        "The Allegheny Portage Railroad operated from 1834 and was primarily used as a portage railway, hauling river boats and barges approximately 36 miles over the divide between the Ohio and the Susquehanna Rivers.",
        "'The Camel' was a unique Dutch railway carriage modified as an inspection car and to carry railway VIPs. Moving the drivers positions to two bulges in the roof gave panoramic views out the front and rear, and the distintice new shape earned the car it's nickname.",
        "In 1966, the New York Central Railroad strapped two J47 jet engines from a bomber to the roof of a commuter car (the M-497 'Black Beetle'). It hit 183 mph, a US rail record that still stands today.",
        "The 'Leaves on the Line' problem is actually about chemistry. When leaves are crushed by train wheels, the pectin and cellulose react with the steel to create a hard, Teflon-like coating called 'black film'. This film is so slippery that it can increase a train’s braking distance by several hundred meters.",
        "Train wheels are conical, not flat. To stay on the tracks during a curve, the wheels are shaped like cones. This allows the outer wheel to travel a slightly larger circumference than the inner wheel, preventing the train from 'scrubbing' or jumping the tracks.",
        "Regenerative braking allows trains to give back. Many modern electric trains act as giant generators. When they brake, the motors run in reverse, converting kinetic energy back into electricity and feeding it back into the overhead lines for other trains to use.",
        "The Maeklong Railway Market in Thailand is literally built on top of active tracks. Eight times a day, vendors pull back their awnings and move their produce just inches away to let the train pass, then immediately slide everything back into place.",
        "New York City has a secret siding known as 'Track 61'. It was built to allow wealthy guests — most notably President Franklin D. Roosevelt — to arrive at the Waldorf Astoria Hotel in a private rail car and take a hidden elevator directly into the building.",
        "Almost every locomotive has a safety device (often a pedal or handle) referred to as a 'dead man's switch', that the driver must press or release at regular intervals. If they fall asleep or become incapacitated, the train automatically applies the emergency brakes.",
        "To gain traction on steep hills or icy tracks, locomotives carry large hoppers of dry sand. A compressed air system blasts the sand directly onto the rail in front of the wheels to provide instant grip.",
        "Before the mid-19th century, every town kept its own 'local time' based on the sun. The need for accurate train schedules forced the UK (and later the US) to adopt a standardized 'Railway Time', which eventually led to the global system of time zones we use today.",
        "The Seikan Tunnel in Japan is the deepest rail tunnel in the world, descending to 790 feet (240 meters) below sea level to connect the islands of Honshu and Hokkaido.",
        "The Katoomba Scenic Railway in Australia’s Blue Mountains is the steepest in the world, with a 52-degree incline. Passengers can adjust their seats to a 'cliffhanger' position.",
        "In Cambodia, locals use 'Norries' — improvised trains made of bamboo platforms and recycled tank wheels powered by small engines. When two meet, the one with fewer passengers is physically lifted off the tracks to let the other pass.",
        "Japan’s Toreiyu Tsubasa Shinkansen features foot baths (ashiyu) inside the carriages, allowing passengers to soak their feet in warm spring water while traveling at high speeds.",
        "New York’s first subway (the Beach Pneumatic Transit, 1870) was a single-block-long tunnel where a giant fan pushed a luxury car back and forth using air pressure.",
        "In 1930, Germany built a railcar called the Rail Zeppelin, which was powered by a massive four-blade propeller at the rear. It reached 143 mph (230 km/h) but was abandoned because the open propeller was too dangerous for station platforms.",
        "In 1920, the body of Britain's 'Unknown Warrior' was brought back from France by train. To honor the fallen, the train was pulled by a locomotive named Black Prince, and the tracks were lined with silent crowds for the entire journey.",
        "In the 1950s, engineers seriously proposed a 'X-12' atomic locomotive powered by a 200-ton nuclear reactor. It was eventually canceled due to safety risks and the extreme cost of uranium.",
        "One of the earliest steam locomotives, the Puffing Devil (1801), was destroyed when its operators left it unattended to go to a pub. The water boiled off, and the engine overheated and burned down.",
        "Rumor has it that when the Lumière brothers showed one of the first films of a train arriving at a station in 1896, the audience was so terrified by the 'oncoming' train that they screamed and ran to the back of the room.",
        "In the 19th century, one proposal for preventing crash injuries involved placing massive bags of wool between carriages to act as giant shock absorber.",
        "The Romney, Hythe & Dymchurch Railway in England is a fully functioning public railway but uses miniature 'one-third scale' steam engines.",
        "During 'Railway Mania,' the British Parliament passed 263 Acts in a single year (1846) to set up new companies. Many were fraudulent 'paper' companies that never built an inch of track but stole millions from investors.",
        "In 1864, the first murder on a British train occurred on the North London Railway. It caused such a panic that it led to the Railways Regulation Act of 1868, which made 'communication cords' (to alert the driver) mandatory in all carriages.",
        "Early Victorian opponents of trains claimed that steam engines would prevent hens from laying eggs and that the 'noxious fumes' would turn the wool of sheep black.",
        "Some 19th-century doctors warned that traveling at 'breakneck speeds' of 15 mph would cause the human body to 'atomize' or explode due to the air pressure.",
        "In cold climates, the 'points' (switches that move the track) have built-in gas or electric heaters to prevent them from freezing shut, which would otherwise paralyze the entire network.",
        "Most passenger trains use a fail-safe air brake system. If a carriage becomes detached, the air pressure is lost, which automatically causes the brakes to 'fail-on,' stopping the runaway cars immediately.",
        "There are two main types of Maglev. EMS (Electromagnetic Suspension) uses attraction to pull the train up toward the track, while EDS (Electrodynamic Suspension) uses repulsion to push it away.",
        "Some high-speed Maglevs use superconducting magnets cooled by liquid nitrogen to -196°C. At these temperatures, the magnets become incredibly powerful and lose all electrical resistance.",
        "The biggest enemy of high-speed trains is air resistance. Concepts like the Hyperloop propose putting Maglev trains inside vacuum tubes. Without air to push against, these trains could theoretically travel at 4,000 mph.",
        "Climbing Steep Grades: Maglev trains can climb much steeper hills (up to a 10% grade) than conventional trains (limited to about 4%). This means they need fewer expensive tunnels and bridges through mountainous areas.",
        "Battery-Electric Locomotives: In areas where overhead wires are too expensive, companies are testing 'FLXdrive' locomotives — giant batteries on wheels that can pull freight for miles without burning a drop of diesel.",
        "Hydrogen Trains: Germany has already launched the world’s first 100% hydrogen-powered passenger fleet. They emit only steam and condensed water, making them completely carbon-neutral.",
        "A railway in Topsham, UK, was once entirely dedicated to hauling 'guano' (seabird droppings), which was so valuable as fertilizer in the 1800s that it was called 'white gold'.",
        "In 1930, a Scottish engineer built a prototype 'flying train' near Glasgow. It was a propeller-driven monorail car that hung from an overhead track, intended to travel at 120 mph above conventional tracks to avoid traffic.",
        "In the 1950s and 60s, the Union Pacific railroad used massive locomotives powered by gas turbine engines (similar to jet engines). They were so incredibly loud that they earned the nickname 'Big Blows'.",
        "Siemens 'Taurus' locomotives are famous for the musical scale they 'play' when starting. The power electronics create a series of tones that sound like a musician running up a scale as the train accelerates.",
        "During the World Wars, many nations used 'land battleships' — trains encased in several inches of steel plating and armed with artillery turrets, anti-aircraft guns, and even tanks mounted on flatbeds.",
        "The Spiral Tunnels: To climb the steep 'Big Hill' in the Canadian Rockies, the Canadian Pacific Railway built two spiral tunnels. The train enters a tunnel, turns a complete circle inside the mountain, and emerges at a much higher elevation directly above where it entered.",
        "Before steam, the Surrey Iron Railway (1803) experimented with 'sailing wagons' on its tracks. However, the wind was too unpredictable, and the experiment was quickly abandoned in favor of horses.",
        "The Railway Politeness Act: In early Victorian England, it was technically a legal requirement for passengers to assist in pushing a train if it became stuck on a hill, though this was rarely enforced.",
        "In the 1850s, London was so overcrowded that the 'London Necropolis Railway' was built. It was a dedicated train service that transported coffins and mourners from Waterloo to a massive new cemetery in Brookwood, Surrey.",
        "The Parliamentary Trains Act of 1844 required every railway company to run at least one train a day that cost no more than one penny per mile, ensuring that even the poorest citizens could afford to travel.",
        "The Arsenalna station in Kyiv, Ukraine, is the deepest in the world at 105.5 meters (346 feet) below ground. The escalator ride to the bottom takes five minutes.",
        "The Pilatus Railway in Switzerland is the steepest rack railway in the world, with a maximum gradient of 48%. It uses a unique 'Locher' rack system with teeth on the side of the rail rather than the top to prevent the wheels from jumping out.",
        "The iron ore train in Mauritania is one of the longest and heaviest in the world (up to 3km long). It is famous because 'hitchhiking' on top of the iron ore piles is a common, though dangerous, way for locals to travel across the desert.",
        "In 2017, the world's first completely solar-powered train began operating in Byron Bay, Australia. It uses flexible solar panels on its roof to charge its batteries at every stop.",
        "Most diesel-electric locomotives don't use brake pads for high-speed slowing. Instead, they turn their motors into generators. The 'drag' of generating electricity slows the train, and the resulting heat is blown out of giant fans on the roof.",
        "Because Maglev trains have no physical contact with the rail, they can 'drift' or move slightly sideways within their guideway to counteract strong crosswinds, making them more stable than wheeled trains in storms.",
        "In Australia, 'AutoHaul' is the world's first fully autonomous, long-distance heavy-haul rail network. Giant trains carrying iron ore travel hundreds of miles across the outback without a single human on board.",
        "Known as the 'Railway King', George Hudson owned one-third of all UK tracks in 1840. He was eventually disgraced for paying dividends to investors using their own capital rather than profits.",
        "When the Liverpool and Manchester Railway opened in 1830, its directors expected to make money from freight. To their shock, passenger demand was so high that they had to build more carriages immediately.",
        "The jagged rocks under the tracks (ballast) are specifically shaped to be irregular so they lock together, holding the tracks in place while allowing water to drain away instantly.",
        "In 1850, an Italian inventor built a locomotive that didn't use steam. Instead, it was powered by four horses walking on a treadmill inside the engine, which then turned the wheels via a gearbox. It successfully reached 7 mph on the London and South Western Railway.",
        "During the construction of the Kenya-Uganda Railway in 1898, work was halted for weeks because two man-eating lions (the Tsavo Maneaters) began hunting and eating the railway workers. They killed dozens of people before the project leader finally shot them.",
        "The Michelin Railcar (1930s) used actual rubber tires filled with air, designed by the Michelin tire company to make the ride quieter. However, they were so expensive and wore out so fast that they were replaced by traditional steel.",
        "The 'Bridge of No Return' is a rail crossing between North and South Korea. While the tracks are technically connected, they have sat unused for decades, maintained only as a symbol of hope for future reunification.",
        "In the early 1900s, some luxury trains in the US and UK featured full-sized marble bathtubs in specialized 'spa cars' for first-class passengers.",
        "To save money during the Great Depression, the Rio Grande Southern Railroad built 'motors — basically a 1920s Buick car body welded to a truck frame with rail wheels—to carry mail and passengers on light-duty mountain tracks.",
        "Steam engines have a valve called a 'blow-off cock' used to eject sediment and sludge from the boiler. If a driver was annoyed by spectators standing too close to the tracks, they would occasionally 'accidentally' blast them with a cloud of hot, dirty steam.",
        "During the construction of the Great Belt Fixed Link in Denmark, a specialized 'work train' reportedly had a direct pipeline to a beer vat to keep the tunnel workers (who were working in high-pressure environments) hydrated and motivated.",
        "A 'slug' is a locomotive that has no engine. It consists only of wheels and motors. It is permanently cabled to a 'mother' locomotive, using the mother's excess electricity to provide extra pulling power at very low speeds in freight yards.",
        "In 1910, inventor Louis Brennan debuted a train that ran on a single rail and stayed upright using massive internal gyroscopes. It could lean into corners like a motorcycle and even carry passengers, including Winston Churchill."
    )
}
