package com.gfd.dailytrainfacts

import java.util.Calendar

object TrainFactsProvider {
    private val facts = listOf(
        "The first steam locomotive was built by Richard Trevithick in 1804.",
        "The fastest train in the world is the Shanghai Maglev, reaching 267 mph.",
        "The Trans-Siberian Railway is the longest railway line in the world.",
        "The first underground railway was the Metropolitan Railway in London, opened in 1863.",
        "Japan's Shinkansen, or 'bullet train', began operation in 1964.",
        "The world's first scheduled passenger steam train service started in 1830.",
        "Standard gauge for most railways is 4 feet 8.5 inches.",
        "The world's highest railway station is Tanggula Railway Station in Tibet.",
        "The Channel Tunnel is the longest undersea tunnel in the world.",
        "The Hogwarts Express in the Harry Potter films is a GWR 4900 Class locomotive.",
        "St. Pancras International is home to the longest champagne bar in Europe.",
        "Railways were used in mines as early as the 1550s.",
        "The Mallard holds the world speed record for steam locomotives at 126 mph.",
        "The Orient Express originally ran from Paris to Istanbul.",
        "The Big Boy is the largest steam locomotive ever built.",
        "A 'locomotive' is the engine that pulls the train cars.",
        "The world's oldest continuously operating railway is the Middleton Railway in Leeds.",
        "The word 'train' comes from the Old French 'trahiner', meaning to draw or pull.",
        "India's railway network is one of the largest in the world, employing over 1.3 million people.",
        "The first railway bridge was built by George Stephenson.",
        "The Dawlish sea wall in Devon is one of the most scenic railway lines in England.",
        "Electric trains were first introduced in the late 19th century.",
        "The Darjeeling Himalayan Railway is a UNESCO World Heritage site.",
        "The first automated driverless train started operating in 1961.",
        "The Eurostar connects London with Paris and Brussels.",
        "The world's busiest railway station is Shinjuku Station in Tokyo.",
        "Maglev trains use magnets to float above the tracks, reducing friction.",
        "The first diesel-electric locomotive was built in 1914.",
        "The Flying Scotsman was the first steam locomotive to officially reach 100 mph.",
        "The TGV is France's high-speed rail service.",
        "The Nottingham Express Transit (NET) is a light rail system serving Nottingham.",
        "Paddington Station was the London terminus for Brunel's Great Western Railway.",
        "The 'Rocket' was an early steam locomotive built by Robert Stephenson.",
        "The Australian Trans-Australian Railway has the world's longest straight stretch of track.",
        "The Grand Central Terminal in New York has 44 platforms.",
        "The first dining car was introduced by the Pullman Palace Car Company.",
        "The 'Iron Horse' was a common nickname for early steam locomotives.",
        "The world's first rack railway was the Mount Washington Cog Railway.",
        "The first electric tramway opened in Berlin in 1881.",
        "St. Pancras Station's Barlow shed was the largest single-span structure in the world in 1868.",
        "The Glacier Express in Switzerland is known as the 'slowest express train'.",
        "The first railway post office ran in the UK in 1838.",
        "The Ghan is a famous passenger train that crosses Australia from north to south.",
        "The first sleeping car was designed by George Pullman.",
        "The world's shortest railway is the Angels Flight in Los Angeles.",
        "The South Devon Railway is a heritage railway running between Totnes and Buckfastleigh.",
        "The first railway tunnel was the Terre-Noire Tunnel in France.",
        "The 'Evening Star' was the last steam locomotive built for British Railways.",
        "The first high-speed rail line was the Tokaido Shinkansen in Japan.",
        "The 'Puffing Billy' is the world's oldest surviving steam locomotive.",
        "The first railway signal was a simple board or flag.",
        "The 'Blue Train' is a luxury train service in South Africa.",
        "Nottingham Station was first opened in 1848 by the Midland Railway.",
        "The Great Western Railway was designed by Isambard Kingdom Brunel.",
        "The first railway in Africa was built in Egypt in 1854.",
        "The 'Indian Pacific' crosses Australia from Sydney to Perth.",
        "The 'Cornish Riviera Express' has been running from London to Penzance since 1904.",
        "The 'Rocky Mountaineer' is a luxury train service in Canada.",
        "The first railway in Asia was built in India in 1853.",
        "The 'Rovos Rail' is another luxury train service in South Africa.",
        "The first railway in China was the Woosung Railway, built in 1876.",
        "The 'Bernina Express' crosses the Alps between Switzerland and Italy.",
        "The first railway in Japan was the Tokyo-Yokohama line, opened in 1872.",
        "The Lynton and Barnstaple Railway in Devon was a famous narrow-gauge line.",
        "The first railway in Russia was the Tsarskoye Selo Railway, opened in 1837.",
        "The 'Venice Simplon-Orient-Express' is a modern luxury version of the original.",
        "The first railway in Canada was the Champlain and St. Lawrence Railroad.",
        "The 'Night Riviera' sleeper train runs from London Paddington to Penzance.",
        "The first railway in Mexico was the Mexican Railway, opened in 1873.",
        "The West Highland Line is often voted one of the most beautiful railway journeys.",
        "The first railway in Brazil was the Mauá Railroad, opened in 1854.",
        "The Settle-Carlisle line is famous for the iconic Ribblehead Viaduct.",
        "The first railway in Argentina was the Buenos Aires Western Railway, opened in 1857.",
        "The Great Central Railway is the UK's only double-track heritage main line.",
        "The first railway in Chile was the Copiapó-Caldera line, opened in 1851.",
        "The Forth Bridge in Scotland is a UNESCO World Heritage site.",
        "The first railway in Peru was the Lima-Callao line, opened in 1851.",
        "The Glenfinnan Viaduct is famous for its appearance in the Harry Potter films.",
        "The first railway in Cuba was the Havana-Bejucal line, opened in 1837.",
        "The Jacobite Steam Train runs from Fort William to Mallaig in Scotland.",
        "The first railway in Australia was the Melbourne and Hobson's Bay Railway, opened in 1854.",
        "The Snowdon Mountain Railway is the only rack and pinion railway in the UK.",
        "The first railway in New Zealand was the Ferrymead Railway, opened in 1863.",
        "The Ffestiniog Railway in Wales is the world's oldest narrow-gauge railway.",
        "The first railway in Indonesia was the Semarang-Tanggung line, opened in 1867.",
        "The 'Caledonian Sleeper' runs from London to various destinations in Scotland.",
        "The first railway in Thailand was the Bangkok-Ayutthaya line, opened in 1896.",
        "The Bluebell Railway was the first preserved standard-gauge heritage line in the UK.",
        "The first railway in Vietnam was the Saigon-Cholon line, opened in 1881.",
        "The Talyllyn Railway was the first railway in the world to be preserved by volunteers.",
        "The first railway in Malaysia was the Taiping-Port Weld line, opened in 1885.",
        "The Keighley \u0026 Worth Valley Railway was a filming location for 'The Railway Children'.",
        "The first railway in the Philippines was the Manila-Dagupan line, opened in 1892.",
        "London Victoria station serves over 70 million passengers a year.",
        "The first railway in Turkey was the Izmir-Aydin line, opened in 1866.",
        "The Severn Valley Railway is one of the most popular heritage lines in the UK.",
        "The first railway in Iran was the Tehran-Ray line, opened in 1888.",
        "Waterloo Station has the largest number of platforms in the UK (24).",
        "The first railway in Iraq was the Baghdad-Samarra line, opened in 1914.",
        "The Paignton and Dartmouth Steam Railway offers beautiful views of the Devon coast.",
        "The first railway in Pakistan was the Karachi-Kotri line, opened in 1861.",
        "The Great Northern Railway once connected Nottingham to London King's Cross.",
        "The first railway in Sri Lanka was the Colombo-Ambepussa line, opened in 1864.",
        "The British Rail Class 43 (HST) is the fastest diesel train in the world.",
        "The first railway in Myanmar was the Yangon-Pyay line, opened in 1877.",
        "The 'Elizabeth Line' is the newest major addition to London's rail network.",
        "The first railway in Bangladesh was the Darshana-Jagati line, opened in 1862.",
        "The North Yorkshire Moors Railway runs through 24 miles of stunning national park.",
        "The first railway in South Korea was the Gyeongin Line, opened in 1899.",
        "The Swanage Railway in Dorset was rebuilt from scratch by volunteers.",
        "The first railway in North Korea was the Gyeongui Line, opened in 1906.",
        "The 'Brighton Belle' was the world's first all-electric Pullman train.",
        "The first railway in Taiwan was the Keelung-Taipei line, opened in 1891.",
        "The Isle of Wight Steam Railway uses vintage locomotives and carriages.",
        "The first railway in Israel was the Jaffa-Jerusalem line, opened in 1892.",
        "The 'Golden Arrow' was a luxury boat train that linked London and Paris.",
        "The first railway in Saudi Arabia was the Dammam-Riyadh line, opened in 1951.",
        "The Romney, Hythe \u0026 Dymchurch Railway is a famous 15-inch gauge line.",
        "The first railway in Jordan was the Hejaz Railway, opened in 1908.",
        "The 'Master Cutler' is a named express train running between London and Sheffield.",
        "The first railway in Lebanon was the Beirut-Damascus line, opened in 1895.",
        "The 'Flying Scotsman' service has run between London and Edinburgh since 1862.",
        "The first railway in Syria was the Damascus-Mzerib line, opened in 1894.",
        "The Ravenglass and Eskdale Railway is one of the oldest and longest narrow-gauge lines.",
        "The first railway in Greece was the Athens-Piraeus line, opened in 1869.",
        "The 'Tees-Thames' express once connected Saltburn to London.",
        "The first railway in Bulgaria was the Ruse-Varna line, opened in 1866.",
        "The 'Devonian' express historically ran from Bradford to Paignton.",
        "The first railway in Romania was the Bucharest-Giurgiu line, opened in 1869.",
        "The 'Robin Hood Line' connects Nottingham to Worksop.",
        "The first railway in Serbia was the Belgrade-Nis line, opened in 1884.",
        "King's Cross Station is famous for its fictional Platform 9¾.",
        "The first railway in Croatia was the Kotoriba-Cakovec line, opened in 1860.",
        "The 'Pines Express' once ran from Manchester to Bournemouth via Bath.",
        "The first railway in Slovenia was the Sentilj-Celje line, opened in 1846.",
        "The 'Thames-Clyde Express' linked London St Pancras and Glasgow Central.",
        "The first railway in Hungary was the Pest-Vac line, opened in 1846.",
        "The 'Royal Scot' was a premier express train of the London Midland and Scottish Railway.",
        "The first railway in Slovakia was the Bratislava-Trnava line, opened in 1840.",
        "The 'Midland Main Line' connects London St Pancras to the East Midlands.",
        "The first railway in the Czech Republic was the Ceske Budejovice-Linz horse-drawn line.",
        "The 'South West Main Line' runs from London Waterloo to Weymouth.",
        "The first railway in Poland was the Upper Silesian Railway, opened in 1842.",
        "The 'East Coast Main Line' is a key artery of the UK rail network.",
        "The first railway in Finland was the Helsinki-Hameenlinna line, opened in 1862.",
        "The 'West Coast Main Line' connects London Euston to Glasgow Central.",
        "The first railway in Norway was the Hoved Line, opened in 1854.",
        "The 'Trans-Pennine Express' routes cross the rugged Pennine hills.",
        "The first railway in Sweden was the Frykstad Railway, opened in 1849.",
        "The 'Cross Country' network is the most extensive in the UK.",
        "The first railway in Denmark splintered from the Copenhagen-Roskilde line in 1847.",
        "The 'Great Eastern Main Line' connects London Liverpool Street to Norwich.",
        "The first railway in the Netherlands was the Amsterdam-Haarlem line, opened in 1839.",
        "The 'Chiltern Main Line' runs from London Marylebone to Birmingham.",
        "The first railway in Belgium was the Brussels-Mechelen line, opened in 1835.",
        "The 'London Overground' is a group of suburban rail lines in London.",
        "The first railway in Luxembourg was the Bettembourg-Luxembourg line, opened in 1859.",
        "The 'Docklands Light Railway' (DLR) is an automated system in East London.",
        "The first railway in Switzerland was the Zurich-Baden line, opened in 1847.",
        "The 'Tyne \u0026 Wear Metro' serves Newcastle upon Tyne and surrounding areas.",
        "The first railway in Austria was the Floridsdorf-Wagram line, opened in 1837.",
        "The 'Glasgow Subway' is the third oldest underground system in the world.",
        "The first railway in Portugal was the Lisbon-Carregado line, opened in 1856.",
        "The 'Merseyrail' system serves the Liverpool City Region.",
        "The first railway in Spain was the Barcelona-Mataró line, opened in 1848.",
        "The 'West Highland Line' features the spectacular Glenfinnan Viaduct.",
        "The first railway in Italy was the Naples-Portici line, opened in 1839.",
        "The 'Far North Line' is the northernmost railway in the UK.",
        "The first railway in Ireland was the Dublin-Kingstown line, opened in 1834.",
        "The 'Heart of Wales Line' is a scenic rural railway.",
        "The first railway in Scotland was the Monkland and Kirkintilloch Railway, opened in 1826.",
        "The 'Cambrian Line' offers beautiful views of the Welsh coast.",
        "The first railway in Wales was the Oystermouth Railway, opened in 1807.",
        "The 'Hope Valley Line' connects Sheffield and Manchester through the Peak District.",
        "The first railway in England was the Stockton and Darlington Railway, opened in 1825.",
        "The 'Riviera Line' runs along the coast from Exeter to Paignton.",
        "The first railway in Germany was the Bavarian Ludwig Railway, opened in 1835.",
        "The 'Cotswold Line' passes through the beautiful Cotswold Hills.",
        "The first railway in France was the Saint-Étienne to Andrézieux line, opened in 1827.",
        "The 'Fen Line' connects Cambridge and King's Lynn.",
        "The first railway in the United States was the Granite Railway, opened in 1826.",
        "The 'Poppy Line' is a heritage railway in North Norfolk.",
        "The first railway in Canada was the Champlain and St. Lawrence Railroad, opened in 1836.",
        "The 'Watercress Line' is a heritage railway in Hampshire.",
        "The first railway in Mexico was the Veracruz-Mexico City line, opened in 1873.",
        "The 'Spa Valley Railway' is a heritage line in Kent.",
        "The first railway in Brazil was the Estrada de Ferro Mauá, opened in 1854.",
        "The 'Epping Ongar Railway' is the longest heritage line in Essex.",
        "The first railway in Argentina was the Ferrocarril Oeste de Buenos Aires, opened in 1857.",
        "The 'St. Charles Streetcar' in New Orleans is the oldest continuously operating streetcar line.",
        "The first railway in Australia was the Sydney-Parramatta line, opened in 1855.",
        "The 'Manx Electric Railway' on the Isle of Man is a historic interurban line.",
        "The first railway in New Zealand was the Christchurch-Ferrymead line, opened in 1863.",
        "The 'Snaefell Mountain Railway' is the only electric mountain railway in the British Isles.",
        "The first railway in India was the Mumbai-Thane line, opened in 1853.",
        "The 'Douglas Bay Horse Tramway' is one of the last remaining of its kind.",
        "The first railway in China was the Woosung Railway, opened in 1876.",
        "The 'Volk's Electric Railway' in Brighton is the oldest electric railway in the world.",
        "The first railway in Japan was the Shimbashi-Yokohama line, opened in 1872.",
        "The 'Hythe Pier Railway' is the oldest continuously operating pier railway.",
        "The first railway in Russia was the Tsarskoye Selo Railway, opened in 1837.",
        "The 'Lynton \u0026 Lynmouth Cliff Railway' is water-powered.",
        "The first railway in South Africa was the Durban-Point line, opened in 1860.",
        "The 'Babbacombe Cliff Railway' in Devon is another famous funicular.",
        "The first railway in Egypt was the Alexandria-Kafr el-Zayyat line, opened in 1854.",
        "The 'South Cliff Lift' in Scarborough was the first funicular in the UK.",
        "The first railway in Morocco was the Tetuan-Rio Martin line, opened in 1859.",
        "The 'Bridgnorth Cliff Railway' is one of the oldest inland funiculars.",
        "The first railway in Algeria was the Algiers-Blida line, opened in 1862.",
        "The 'East Hill Lift' in Hastings is the steepest funicular in the UK.",
        "The first railway in Tunisia was the Tunis-La Goulette line, opened in 1872.",
        "The 'Leas Lift' in Folkestone is a unique water-balance funicular.",
        "The first railway in Ethiopia was the Djibouti-Addis Ababa line, opened in 1917.",
        "The 'Saltburn Cliff Lift' is one of the oldest water-balanced funiculars in operation.",
        "The first railway in Kenya was the Uganda Railway, opened in 1901.",
        "The 'Southend Pier Railway' is the longest pier railway in the world.",
        "The first railway in Nigeria was the Lagos-Ibadan line, opened in 1901.",
        "The 'Seaton Tramway' in Devon operates narrow-gauge trams.",
        "The first railway in Ghana was the Sekondi-Tarkwa line, opened in 1901.",
        "The 'Crich Tramway Village' is home to the National Tramway Museum.",
        "The first railway in Sudan was the Wadi Halfa-Sarras line, opened in 1875.",
        "The 'Blackpool Tramway' is the only remaining first-generation tramway in the UK.",
        "The first railway in Zimbabwe was the Vryburg-Bulawayo line, opened in 1897.",
        "The 'Edinburgh Trams' returned to the city streets in 2014.",
        "The first railway in Zambia was the Bulawayo-Victoria Falls line, opened in 1904.",
        "The 'Manchester Metrolink' is the largest light rail system in the UK.",
        "The first railway in Tanzania was the Tanga-Korogwe line, opened in 1902.",
        "The 'West Midlands Metro' connects Birmingham and Wolverhampton.",
        "The first railway in Uganda was the Uganda Railway, opened in 1901.",
        "The 'Sheffield Supertram' features a unique design.",
        "The first railway in Angola was the Luanda Railway, opened in 1888.",
        "The 'Luas' is the light rail system serving Dublin.",
        "The first railway in Mozambique was the Beira-Umtali line, opened in 1898.",
        "The 'Translink' Enterprise service connects Belfast and Dublin.",
        "The first railway in Namibia was the Swakopmund-Windhoek line, opened in 1902.",
        "The 'Grand Junction Railway' once linked Birmingham to the Liverpool \u0026 Manchester Railway.",
        "The first railway in Botswana was the Mafeking-Bulawayo line, opened in 1897.",
        "The 'London and North Western Railway' was once the largest joint-stock company in the world.",
        "The first railway in Senegal was the Dakar-Saint Louis line, opened in 1885.",
        "The 'Midland Railway' had its headquarters in Derby, near Nottingham.",
        "The first railway in Ivory Coast was the Abidjan-Niger Railway, opened in 1905.",
        "The 'North Eastern Railway' had the largest collection of steam locomotives in the UK.",
        "The first railway in Cameroon was the Douala-Nkongsamba line, opened in 1911.",
        "The 'Great South \u0026 West Railway' was the largest railway in Ireland.",
        "The first railway in Gabon was the Trans-Gabon Railway, opened in 1978.",
        "The 'Somerset \u0026 Dorset Joint Railway' was famously known as the 'Slow and Dirty'.",
        "The first railway in Congo (Kinshasa) was the Matadi-Kinshasa line, opened in 1898.",
        "The 'Lancashire \u0026 Yorkshire Railway' had a very dense network of lines.",
        "The first railway in Madagascar was the Tananarive-Tamatave line, opened in 1913.",
        "The 'London, Brighton and South Coast Railway' was famous for its elegant locomotives.",
        "The first railway in Mauritius was the North line, opened in 1864.",
        "The 'Great North of Scotland Railway' served the north-east of the country.",
        "The first railway in Reunion was the Saint-Denis to Saint-Pierre line, opened in 1882.",
        "The 'Highland Railway' struggled with steep gradients and snowy weather.",
        "The first railway in Seychelles was a small industrial line on Silhouette Island.",
        "The 'Cambrian Railways' served the heart of Wales.",
        "The first railway in Cape Verde was a small industrial line on Sal Island.",
        "The 'Rhymney Railway' was a key coal-carrying line in South Wales.",
        "The first railway in Comoros was a small industrial line on Anjouan Island.",
        "The 'Taff Vale Railway' was another major coal-carrying line.",
        "The first railway in Mayotte was a small industrial line on Dzaoudzi Island.",
        "The 'Barry Railway' built its own dock to compete with Cardiff.",
        "The first railway in Djibouti was the Djibouti-Addis Ababa line, opened in 1901.",
        "The 'Furness Railway' served the industrial areas of Cumbria.",
        "The first railway in Eritrea was the Massawa-Asmara line, opened in 1911.",
        "The 'Maryport \u0026 Carlisle Railway' was a small but profitable line.",
        "The first railway in Ethiopia was the Djibouti-Addis Ababa line, opened in 1917.",
        "The 'North Staffordshire Railway' was known as the 'Knotty'.",
        "The first railway in Somalia was the Mogadishu-Villabruzzi Railway, opened in 1914.",
        "The 'Hull \u0026 Barnsley Railway' was built to break the monopoly of the NER.",
        "The first railway in Libya was the Benghazi-Barce line, opened in 1911.",
        "The 'Stratford-upon-Avon \u0026 Midland Junction Railway' was formed from several small lines.",
        "The first railway in Liberia was the Bomi Hills-Monrovia line, opened in 1951.",
        "The 'Isle of Wight Railway' served the eastern part of the island.",
        "The first railway in Sierra Leone was the Freetown-Songo line, opened in 1897.",
        "The 'Belfast \u0026 County Down Railway' served the area south of Belfast.",
        "The first railway in Guinea was the Conakry-Kankan line, opened in 1914.",
        "The 'Midland Great Western Railway' was the third largest in Ireland.",
        "The first railway in Togo was the Lome-Aneho line, opened in 1905.",
        "The 'Dublin \u0026 South Eastern Railway' was known for its scenic coastal line.",
        "The first railway in Benin was the Cotonou-Ouidah line, opened in 1906.",
        "The 'Clogher Valley Railway' was a famous Irish narrow-gauge line.",
        "The first railway in Burkina Faso was the Abidjan-Niger Railway, opened in 1933.",
        "The 'Listowel \u0026 Ballybunion Railway' was a unique Lartigue monorail.",
        "The first railway in Mali was the Dakar-Niger Railway, opened in 1904.",
        "The 'Schull \u0026 Skibbereen Railway' was another notable Irish narrow-gauge line.",
        "The first railway in Niger was the Cotonou-Parakou line, extended to Niamey in 2014.",
        "The 'Tralee \u0026 Dingle Light Railway' was the westernmost railway in Europe.",
        "The first railway in Chad was a small industrial line near Lake Chad.",
        "The 'County Donegal Railways' had the largest narrow-gauge system in Ireland.",
        "The first railway in Central African Republic was a small industrial line.",
        "The 'London \u0026 Greenwich Railway' was the first to be built on a brick viaduct.",
        "The first railway in Equatorial Guinea was a small industrial line on Bioko Island.",
        "The 'London \u0026 Blackwall Railway' originally used cable haulage.",
        "The first railway in Sao Tome and Principe was a small industrial line.",
        "The 'Eastern Counties Railway' was notorious for its poor service.",
        "The first railway in Rwanda was a small industrial line.",
        "The 'South Eastern \u0026 Chatham Railway' was a working union of two rivals.",
        "The first railway in Burundi was a small industrial line.",
        "The 'Great Central' motto was 'Forward'.",
        "The first railway in Malawi was the Shire Highlands Railway, opened in 1908.",
        "The 'Great Western' motto was 'Dominine Dirige Nos'.",
        "The first railway in Swaziland was the Swaziland Railway, opened in 1964.",
        "The 'Southern' motto was 'Semper Sursum'.",
        "The first railway in Lesotho was the Maseru Branch line, opened in 1905.",
        "The 'London Midland \u0026 Scottish' was formed during the 1923 grouping.",
        "The first railway in Gambia was a small industrial line.",
        "The 'London \u0026 North Eastern' was another of the 'Big Four' companies.",
        "The first railway in Guinea-Bissau was a small industrial line.",
        "The 'Southern Railway' was the smallest of the Big Four.",
        "The first railway in Cape Verde was a small industrial line.",
        "The 'Great Western Railway' was the only one to keep its name in 1923.",
        "The first railway in Seychelles was a small industrial line.",
        "The 'British Railways' was formed by nationalisation in 1948.",
        "The first railway in Saint Helena was the Ladder Hill Railway, opened in 1829.",
        "The 'InterCity 125' was a revolutionary high-speed diesel train.",
        "The first railway in Falkland Islands was the Camber Railway, opened in 1915.",
        "The 'Advanced Passenger Train' (APT) was a tilt-train that was ahead of its time.",
        "The first railway in Bermuda was the Bermuda Railway, opened in 1931.",
        "The 'Eurostar' started running through the Channel Tunnel in 1994.",
        "The first railway in Bahamas was a small industrial line.",
        "The 'High Speed 1' (HS1) connects London St Pancras to the Channel Tunnel.",
        "The first railway in Jamaica was the Western Jamaica Connecting Railway, opened in 1845.",
        "The 'Crossrail' project created the Elizabeth Line in London.",
        "The first railway in Barbados was the Barbados Railway, opened in 1881.",
        "The 'Thameslink' network runs from Bedford to Brighton.",
        "The first railway in Trinidad and Tobago was the Trinidad Government Railway, opened in 1876.",
        "The 'Southern' network is the busiest in the UK.",
        "The first railway in Puerto Rico was the Ferrocarril de Circunvalación, opened in 1891.",
        "The 'South Western Railway' operates the busiest station in the UK (Waterloo).",
        "The first railway in Haiti was the Port-au-Prince Tramway, opened in 1878.",
        "The 'Avanti West Coast' service features high-speed tilting trains.",
        "The first railway in Dominican Republic was the Samaná-Santiago Railway, opened in 1887.",
        "The 'LNER' Azuma trains are some of the fastest in the UK.",
        "The first railway in Saint Kitts and Nevis was the Saint Kitts Sugar Factory Railway, opened in 1912.",
        "The 'Great Western Railway' uses IET trains inspired by Japanese technology.",
        "The first railway in Antigua and Barbuda was a sugar railway, opened in 1903.",
        "The 'ScotRail' network covers the whole of Scotland.",
        "The first railway in Dominica was a forest railway, opened in 1910.",
        "The 'Transport for Wales' is investing in brand new trains for the whole network.",
        "The first railway in Saint Lucia was a sugar railway, opened in 1902.",
        "The 'Northern' network connects the major cities of the North of England.",
        "The first railway in Saint Vincent and the Grenadines was a sugar railway.",
        "The 'West Midlands Railway' serves the heart of the country.",
        "The first railway in Grenada was a small industrial line.",
        "The 'East Midlands Railway' runs fast services to London St Pancras.",
        "The first railway in Suriname was the Lawa Railway, opened in 1903.",
        "The 'Greater Anglia' network has been completely transformed with new trains.",
        "The first railway in Guyana was the Demerara-Berbice Railway, opened in 1848.",
        "The 'c2c' service between London and Essex is known for its reliability.",
        "The first railway in French Guiana was a small industrial line.",
        "The 'Southeastern' network serves Kent and East Sussex.",
        "The first railway in South Georgia and South Sandwich Islands was a whaling railway.",
        "The 'Chiltern Railways' is known for its high customer satisfaction.",
        "The first railway in British Indian Ocean Territory was a small industrial line.",
        "The 'Heathrow Express' is the fastest way between Central London and the airport.",
        "The first railway in Christmas Island was a phosphate railway.",
        "The 'Gatwick Express' provides a dedicated service to Gatwick Airport.",
        "The first railway in Nauru was a phosphate railway, opened in 1907.",
        "The 'Stansted Express' connects the City of London to Stansted Airport.",
        "The first railway in Fiji was a sugar railway, opened in 1882.",
        "The 'London Underground' has 11 lines and 272 stations.",
        "The first railway in Solomon Islands was a small industrial line.",
        "The 'Glasgow Subway' is known affectionately as the 'Clockwork Orange'.",
        "The first railway in Vanuatu was a small industrial line.",
        "The 'Tyne \u0026 Wear Metro' uses a unique mix of heavy and light rail technology.",
        "The first railway in New Caledonia was the Noumea-Paita line, opened in 1901.",
        "The 'Docklands Light Railway' was originally built using existing railway infrastructure.",
        "The first railway in Guam was a small military railway.",
        "The 'Elizabeth Line' is named after Queen Elizabeth II.",
        "The first railway in Northern Mariana Islands was a small industrial line.",
        "The 'Channel Tunnel' is the longest undersea tunnel in the world (already mentioned).",
        "The first railway in American Samoa was a small military railway.",
        "The 'Humber Bridge' was never designed to carry a railway (fun fact!).",
        "The first railway in Palau was a small industrial line.",
        "The 'Forth Bridge' is iconic for its cantilever design.",
        "The first railway in Marshall Islands was a small industrial line.",
        "The 'Tay Bridge Disaster' in 1879 led to the design of the current bridge.",
        "The first railway in Kiribati was a small industrial line.",
        "The 'Ribblehead Viaduct' is 400 metres long and has 24 arches.",
        "The first railway in Tuvalu was a small industrial line.",
        "The 'Glenfinnan Viaduct' has 21 arches.",
        "The first railway in Micronesia was a small industrial line.",
        "The 'Bennerley Viaduct' near Nottingham is a rare iron structure.",
        "The first railway in Tonga was a small industrial line.",
        "The 'St. Pancras Hotel' is a masterpiece of Gothic Revival architecture.",
        "The first railway in Samoa was a small industrial line.",
        "The 'Victoria Station' in Nottingham once had a very deep tunnel.",
        "The first railway in Niue was a small industrial line.",
        "The 'Old Dalby Test Track' is a key facility for testing new trains in the UK.",
        "The first railway in Cook Islands was a small industrial line.",
        "The 'Great Western' is often called 'God's Wonderful Railway'.",
        "The first railway in Wallis and Futuna was a small industrial line.",
        "The 'Dawlish Sea Wall' is one of Brunel's most daring engineering feats.",
        "The first railway in Tokelau was a small industrial line.",
        "The 'Midland Main Line' was electrified to Corby in 2021.",
        "The first railway in Pitcairn Islands was a small industrial line.",
        "The 'Big Boy' locomotive 4014 is the only one currently operating."
    )

    fun getFactForToday(): String {
        val calendar = Calendar.getInstance()
        val timeInMillis = calendar.timeInMillis
        // Adjust for local timezone offset to ensure "00:00 local device time"
        val localTimeInMillis = timeInMillis + calendar.timeZone.getOffset(timeInMillis)
        val daysSinceEpoch = localTimeInMillis / (24 * 60 * 60 * 1000)
        
        // Using a modulus with facts.size (which is 366) ensures a stable rotation.
        // Since we have at least 366 facts, no fact repeats within any 366-day window.
        val index = (daysSinceEpoch % facts.size).toInt()
        return facts[index]
    }
}
